Solve error when canceling formula edition
  - An error was shown when we treid to cancel a formula edition
    but decided to keep editing (cancel the cancelation).
  - It's been solved by changing the place where the function which caused the
    error was called.
  - Updated changelog.md
  - Fix the 'demo-html5-generic' and remove 'Jest'

Also on this commit:

- Fix 'demo-html5-generic': chokidar is missing

  The demo didn't work when running the 'start' command.

  This error appeared on console:

  > 'Error: No version of chokidar is available.
  Tried chokidar@2 and chokidar@3.'
  > chokidar@3: Error: Cannot find module 'chokidar'

  To fix this, chokidar needed to be installed manually.

- Fix vulnerabilities with an audit and remove jest

  The 'jest' dependency was still present at the root of the project.

  This library was supposed to be removed from the project before.
  This change fixes this.

- Update package-lock's on all demos.

#taskid 16499